schemaVersion: 2.1.0
metadata:
  name: microservices-demo
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: frontend
    container:
      image: quay.io/mloriedo/microservices-demo-frontend:latest
      volumeMounts:
        - name: checode
          path: /checode
      memoryLimit: 2G
      memoryRequest: 256Mi
      cpuLimit: 500m
      cpuRequest: 30m
      endpoints:
        - name: frontend
          targetPort: 8079
      args: ["/checode/entrypoint-volume.sh"]
      env: [{name: CODE_HOST, value: "0.0.0.0"}]
  - name: catalogue
    container:
      image: weaveworksdemos/catalogue:0.3.5
      cpuLimit: 200m
      memoryLimit: 200Mi
      cpuRequest: 100m
      memoryRequest: 100Mi
      command:
        - sh
      args:
        - '-c'
        - 'sleep 30 && /app -port 8080 -DSN "catalogue_user:default_password@tcp(localhost:3306)/socksdb"'
      endpoints:
        - name: catalogue
          targetPort: 8080
          exposure: internal
  - name: catalogue-db
    container:
      image: weaveworksdemos/catalogue-db:0.3.0
      cpuLimit: 200m
      memoryLimit: 300Mi
      cpuRequest: 100m
      memoryRequest: 100Mi
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: fake_password
      - name: MYSQL_DATABASE
        value: socksdb
      volumeMounts:
        - name: catalogue-volume
          path: /var/lib/mysql
      endpoints:
        - name: catalogue-db
          targetPort: 3360
          exposure: internal
  - name: catalogue-volume
    volume:
      ephemeral: true
commands:
  - id: init-project
    exec:
      component: frontend
      commandLine: yarn install
      workingDir: $PROJECT_SOURCE
events:
  postStart:
    - init-project